import { t, v, type IconPuzzle } from "./types";

export const ICONS: IconPuzzle[] = [
  // ---------- EASY ----------
  { id: "ic-e-01", level: "easy", icons: "🌊🚢🐘🌈",
    choices: [t("Noah and the flood", "Si Noe at ang baha"), t("Jonah and the big fish", "Si Jonas at ang malaking isda"), t("The Tower of Babel", "Ang Tore ng Babel"), t("Moses and the Red Sea", "Si Moises at ang Dagat na Pula")],
    ref: v("Genesis", 7, "17-24") },
  { id: "ic-e-02", level: "easy", icons: "🐋🙏🌿",
    choices: [t("Jonah and the big fish", "Si Jonas at ang malaking isda"), t("Noah and the flood", "Si Noe at ang baha"), t("Daniel in the lions' den", "Si Daniel sa yungib ng mga leon"), t("Jesus calms the storm", "Pinatigil ni Jesus ang unos")],
    ref: v("Jonah", 1, "17") },
  { id: "ic-e-03", level: "easy", icons: "🧒🪨👊🗡️",
    choices: [t("David and Goliath", "Si David at si Goliat"), t("Samson and the Philistines", "Si Samson at ang mga Filisteo"), t("Gideon and the Midianites", "Si Gideon at ang mga Midianita"), t("Joshua at Jericho", "Si Josue sa Jerico")],
    ref: v("1 Samuel", 17, "40-50") },
  { id: "ic-e-04", level: "easy", icons: "🍎🐍🌳",
    choices: [t("Adam and Eve in the garden", "Sina Adan at Eba sa hardin"), t("Cain and Abel", "Sina Cain at Abel"), t("Noah and the flood", "Si Noe at ang baha"), t("The burning bush", "Ang nagniningas na palumpong")],
    ref: v("Genesis", 3, "1-13") },
  { id: "ic-e-05", level: "easy", icons: "🏜️🌊🪄",
    choices: [t("Moses and the Red Sea", "Si Moises at ang Dagat na Pula"), t("Jesus walks on water", "Lumakad si Jesus sa tubig"), t("Noah and the flood", "Si Noe at ang baha"), t("Joshua crosses the Jordan", "Tumawid si Josue sa Jordan")],
    ref: v("Exodus", 14, "21-22") },
  { id: "ic-e-06", level: "easy", icons: "🦁🙏🌙",
    choices: [t("Daniel in the lions' den", "Si Daniel sa yungib ng mga leon"), t("David and the lion", "Si David at ang leon"), t("Samson and the lion", "Si Samson at ang leon"), t("Jonah and the big fish", "Si Jonas at ang malaking isda")],
    ref: v("Daniel", 6, "16-23") },
  { id: "ic-e-07", level: "easy", icons: "⭐🐑👶🐪",
    choices: [t("The birth of Jesus", "Ang pagsilang ni Jesus"), t("The baptism of Jesus", "Ang pagbibinyag kay Jesus"), t("The birth of Moses", "Ang pagsilang ni Moises"), t("The Last Supper", "Ang Huling Hapunan")],
    ref: v("Luke", 2, "1-20") },
  { id: "ic-e-08", level: "easy", icons: "🔥🌿👞",
    choices: [t("Moses and the burning bush", "Si Moises at ang nagniningas na palumpong"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo"), t("Pentecost", "Ang Pentecostes"), t("Shadrach, Meshach and Abednego", "Sina Sadrac, Mesac at Abednego")],
    ref: v("Exodus", 3, "1-6") },
  { id: "ic-e-09", level: "easy", icons: "🧱🗼🗣️",
    choices: [t("The Tower of Babel", "Ang Tore ng Babel"), t("The walls of Jericho", "Ang mga pader ng Jerico"), t("Nehemiah rebuilds the wall", "Itinayong muli ni Nehemias ang pader"), t("Noah and the flood", "Si Noe at ang baha")],
    ref: v("Genesis", 11, "1-9") },
  { id: "ic-e-10", level: "easy", icons: "🍞🐟👥",
    choices: [t("Jesus feeds the five thousand", "Pinakain ni Jesus ang limang libo"), t("The Last Supper", "Ang Huling Hapunan"), t("The wedding at Cana", "Ang kasal sa Cana"), t("The miraculous catch of fish", "Ang kamangha-manghang huli ng isda")],
    ref: v("John", 6, "5-13") },
  { id: "ic-e-11", level: "easy", icons: "🌊🚶😨",
    choices: [t("Jesus walks on water", "Lumakad si Jesus sa tubig"), t("Moses and the Red Sea", "Si Moises at ang Dagat na Pula"), t("Jonah and the big fish", "Si Jonas at ang malaking isda"), t("Jesus is baptized", "Binyagan si Jesus")],
    ref: v("Matthew", 14, "22-33") },
  { id: "ic-e-12", level: "easy", icons: "✝️🪨🌅",
    choices: [t("The resurrection of Jesus", "Ang muling pagkabuhay ni Jesus"), t("The raising of Lazarus", "Ang pagbuhay kay Lazaro"), t("The birth of Jesus", "Ang pagsilang ni Jesus"), t("Pentecost", "Ang Pentecostes")],
    ref: v("Matthew", 28, "1-8") },
  { id: "ic-e-13", level: "easy", icons: "⛰️📜🔟",
    choices: [t("Moses receives the Ten Commandments", "Tinanggap ni Moises ang Sampung Utos"), t("The Sermon on the Mount", "Ang Sermon sa Bundok"), t("The burning bush", "Ang nagniningas na palumpong"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo")],
    ref: v("Exodus", 20, "1-17") },
  { id: "ic-e-14", level: "easy", icons: "💇💪🏛️",
    choices: [t("Samson and Delilah", "Sina Samson at Delila"), t("David and Goliath", "Si David at si Goliat"), t("Gideon's 300 men", "Ang 300 tauhan ni Gideon"), t("Absalom's rebellion", "Ang paghihimagsik ni Absalom")],
    ref: v("Judges", 16, "17-30") },
  { id: "ic-e-15", level: "easy", icons: "🧥💭🕳️",
    choices: [t("Joseph and his brothers", "Si Jose at ang kanyang mga kapatid"), t("Jacob and Esau", "Sina Jacob at Esau"), t("Daniel in the lions' den", "Si Daniel sa yungib ng mga leon"), t("Cain and Abel", "Sina Cain at Abel")],
    ref: v("Genesis", 37, "23-28") },
  { id: "ic-e-16", level: "easy", icons: "🔥🏙️🧂",
    choices: [t("Sodom and Lot's wife", "Ang Sodoma at ang asawa ni Lot"), t("The walls of Jericho", "Ang mga pader ng Jerico"), t("Noah and the flood", "Si Noe at ang baha"), t("The Tower of Babel", "Ang Tore ng Babel")],
    ref: v("Genesis", 19, "24-26") },
  { id: "ic-e-17", level: "easy", icons: "🍞🍷👥",
    choices: [t("The Last Supper", "Ang Huling Hapunan"), t("Jesus feeds the five thousand", "Pinakain ni Jesus ang limang libo"), t("The wedding at Cana", "Ang kasal sa Cana"), t("The prodigal son's feast", "Ang handaan para sa alibughang anak")],
    ref: v("Luke", 22, "14-20") },
  { id: "ic-e-18", level: "easy", icons: "🌳👀💰",
    choices: [t("Zacchaeus", "Si Zaqueo"), t("Nicodemus", "Si Nicodemo"), t("Matthew the tax collector", "Si Mateo na maniningil ng buwis"), t("Bartimaeus", "Si Bartimeo")],
    ref: v("Luke", 19, "1-10") },
  { id: "ic-e-19", level: "easy", icons: "🛣️🤕🐴",
    choices: [t("The Good Samaritan", "Ang Mabuting Samaritano"), t("The Prodigal Son", "Ang Alibughang Anak"), t("The Lost Sheep", "Ang Nawawalang Tupa"), t("The Sower", "Ang Manghahasik")],
    ref: v("Luke", 10, "30-37") },
  { id: "ic-e-20", level: "easy", icons: "🐖💰🏠",
    choices: [t("The Prodigal Son", "Ang Alibughang Anak"), t("The Good Samaritan", "Ang Mabuting Samaritano"), t("The Lost Coin", "Ang Nawawalang Pilak"), t("Joseph and his brothers", "Si Jose at ang kanyang mga kapatid")],
    ref: v("Luke", 15, "11-24") },

  // ---------- MEDIUM ----------
  { id: "ic-m-01", level: "medium", icons: "🏺🔦🎺",
    choices: [t("Gideon and the 300 men", "Si Gideon at ang 300 tauhan"), t("Joshua at Jericho", "Si Josue sa Jerico"), t("Samson and the Philistines", "Si Samson at ang mga Filisteo"), t("David and Goliath", "Si David at si Goliat")],
    ref: v("Judges", 7, "15-22") },
  { id: "ic-m-02", level: "medium", icons: "🔥🐂⛰️",
    choices: [t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo"), t("Moses and the burning bush", "Si Moises at ang nagniningas na palumpong"), t("Abraham and Isaac on the mountain", "Sina Abraham at Isaac sa bundok"), t("Pentecost", "Ang Pentecostes")],
    ref: v("1 Kings", 18, "30-39") },
  { id: "ic-m-03", level: "medium", icons: "🌾👩👵",
    choices: [t("Ruth and Naomi", "Sina Ruth at Noemi"), t("Esther and the king", "Sina Esther at ang hari"), t("Hannah's prayer", "Ang panalangin ni Ana"), t("Rebekah at the well", "Si Rebeka sa balon")],
    ref: v("Ruth", 1, "16-17") },
  { id: "ic-m-04", level: "medium", icons: "👸🏰🙏",
    choices: [t("Queen Esther", "Reyna Esther"), t("Ruth and Naomi", "Sina Ruth at Noemi"), t("The Queen of Sheba", "Ang Reyna ng Sheba"), t("Deborah the judge", "Si Debora na hukom")],
    ref: v("Esther", 5, "1-3") },
  { id: "ic-m-05", level: "medium", icons: "🎺🧱🏙️",
    choices: [t("The fall of Jericho", "Ang pagbagsak ng Jerico"), t("Gideon and the 300 men", "Si Gideon at ang 300 tauhan"), t("The Tower of Babel", "Ang Tore ng Babel"), t("Nehemiah rebuilds the wall", "Itinayong muli ni Nehemias ang pader")],
    ref: v("Joshua", 6, "15-20") },
  { id: "ic-m-06", level: "medium", icons: "🐏⛰️👦🔥",
    choices: [t("Abraham and Isaac", "Sina Abraham at Isaac"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo"), t("Cain and Abel", "Sina Cain at Abel"), t("Jacob and Esau", "Sina Jacob at Esau")],
    ref: v("Genesis", 22, "9-13") },
  { id: "ic-m-07", level: "medium", icons: "🪜😴👼",
    choices: [t("Jacob's ladder", "Ang hagdan ni Jacob"), t("Jacob wrestles with God", "Nakipagbuno si Jacob sa Diyos"), t("Joseph's dreams", "Ang mga panaginip ni Jose"), t("Abraham and the stars", "Si Abraham at ang mga bituin")],
    ref: v("Genesis", 28, "10-15") },
  { id: "ic-m-08", level: "medium", icons: "🔥🧍🧍🧍",
    choices: [t("The fiery furnace", "Ang nagniningas na hurno"), t("Daniel in the lions' den", "Si Daniel sa yungib ng mga leon"), t("The burning bush", "Ang nagniningas na palumpong"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo")],
    ref: v("Daniel", 3, "19-27") },
  { id: "ic-m-09", level: "medium", icons: "🍷✋🧱",
    choices: [t("The writing on the wall", "Ang sulat sa dingding"), t("The fiery furnace", "Ang nagniningas na hurno"), t("The Last Supper", "Ang Huling Hapunan"), t("Daniel in the lions' den", "Si Daniel sa yungib ng mga leon")],
    ref: v("Daniel", 5, "5-6") },
  { id: "ic-m-10", level: "medium", icons: "💡🐴👁️",
    choices: [t("Paul's conversion on the road to Damascus", "Ang pagbabagong-buhay ni Pablo sa daan patungong Damasco"), t("Peter's vision of the sheet", "Ang pangitain ni Pedro tungkol sa kumot"), t("Jesus is transfigured", "Nagbagong-anyo si Jesus"), t("Philip and the Ethiopian", "Si Felipe at ang Etiope")],
    ref: v("Acts", 9, "3-9") },
  { id: "ic-m-11", level: "medium", icons: "⚰️🪨😭",
    choices: [t("The raising of Lazarus", "Ang pagbuhay kay Lazaro"), t("The resurrection of Jesus", "Ang muling pagkabuhay ni Jesus"), t("Jairus' daughter", "Ang anak ni Jairo"), t("The widow's son at Nain", "Ang anak ng balo sa Nain")],
    ref: v("John", 11, "38-44") },
  { id: "ic-m-12", level: "medium", icons: "🍷💧💒",
    choices: [t("The wedding at Cana", "Ang kasal sa Cana"), t("The Last Supper", "Ang Huling Hapunan"), t("Jesus feeds the five thousand", "Pinakain ni Jesus ang limang libo"), t("Jesus and the Samaritan woman", "Si Jesus at ang babaeng Samaritana")],
    ref: v("John", 2, "1-11") },
  { id: "ic-m-13", level: "medium", icons: "🌱🐦🪨",
    choices: [t("The parable of the Sower", "Ang talinghaga ng Manghahasik"), t("The parable of the Lost Sheep", "Ang talinghaga ng Nawawalang Tupa"), t("The parable of the Mustard Seed", "Ang talinghaga ng Butil ng Mustasa"), t("The Good Samaritan", "Ang Mabuting Samaritano")],
    ref: v("Matthew", 13, "3-8") },
  { id: "ic-m-14", level: "medium", icons: "🐓😢🔥",
    choices: [t("Peter denies Jesus", "Itinatwa ni Pedro si Jesus"), t("Judas betrays Jesus", "Pinagtaksilan ni Judas si Jesus"), t("Jesus prays in Gethsemane", "Nanalangin si Jesus sa Getsemani"), t("Peter walks on water", "Lumakad si Pedro sa tubig")],
    ref: v("Luke", 22, "54-62") },
  { id: "ic-m-15", level: "medium", icons: "🌙📖👴",
    choices: [t("Nicodemus visits Jesus at night", "Dumalaw si Nicodemo kay Jesus nang gabi"), t("Zacchaeus", "Si Zaqueo"), t("Simeon in the temple", "Si Simeon sa templo"), t("The rich young ruler", "Ang mayamang batang pinuno")],
    ref: v("John", 3, "1-16") },
  { id: "ic-m-16", level: "medium", icons: "🧖💦7️⃣",
    choices: [t("Naaman is healed of leprosy", "Gumaling si Naaman sa ketong"), t("Jesus heals ten lepers", "Pinagaling ni Jesus ang sampung ketongin"), t("The pool of Bethesda", "Ang tangke ng Betesda"), t("Moses and the Red Sea", "Si Moises at ang Dagat na Pula")],
    ref: v("2 Kings", 5, "9-14") },
  { id: "ic-m-17", level: "medium", icons: "🙏👶🛕",
    choices: [t("Hannah and Samuel", "Sina Ana at Samuel"), t("Ruth and Naomi", "Sina Ruth at Noemi"), t("Mary and baby Jesus", "Si Maria at ang sanggol na si Jesus"), t("Sarah and Isaac", "Sina Sara at Isaac")],
    ref: v("1 Samuel", 1, "9-28") },
  { id: "ic-m-18", level: "medium", icons: "👶⚖️👑",
    choices: [t("The wisdom of Solomon", "Ang karunungan ni Solomon"), t("Moses in the basket", "Si Moises sa basket"), t("Queen Esther", "Reyna Esther"), t("David and Bathsheba", "Sina David at Batsheba")],
    ref: v("1 Kings", 3, "16-28") },
  { id: "ic-m-19", level: "medium", icons: "🔥🕊️🗣️",
    choices: [t("Pentecost", "Ang Pentecostes"), t("The baptism of Jesus", "Ang pagbibinyag kay Jesus"), t("The Tower of Babel", "Ang Tore ng Babel"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo")],
    ref: v("Acts", 2, "1-4") },
  { id: "ic-m-20", level: "medium", icons: "🪙🪙👩⛪",
    choices: [t("The widow's offering", "Ang abuloy ng balo"), t("The lost coin", "Ang nawawalang pilak"), t("Jesus cleanses the temple", "Nilinis ni Jesus ang templo"), t("The Parable of the Talents", "Ang talinghaga ng mga talento")],
    ref: v("Mark", 12, "41-44") },

  // ---------- HARD ----------
  { id: "ic-h-01", level: "hard", icons: "🫏🗣️⚔️",
    choices: [t("Balaam's donkey", "Ang asno ni Balaam"), t("Jesus enters Jerusalem", "Pumasok si Jesus sa Jerusalem"), t("Samson and the donkey's jawbone", "Si Samson at ang panga ng asno"), t("Abraham and Isaac", "Sina Abraham at Isaac")],
    ref: v("Numbers", 22, "21-31") },
  { id: "ic-h-02", level: "hard", icons: "🔥🐎🌪️",
    choices: [t("Elijah taken up to heaven", "Si Elias ay dinala sa langit"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo"), t("Pentecost", "Ang Pentecostes"), t("The ascension of Jesus", "Ang pag-akyat ni Jesus sa langit")],
    ref: v("2 Kings", 2, "11-12") },
  { id: "ic-h-03", level: "hard", icons: "🏹🤝🧒",
    choices: [t("Jonathan and David's friendship", "Ang pagkakaibigan nina Jonatan at David"), t("David and Goliath", "Si David at si Goliat"), t("Saul chases David", "Hinabol ni Saul si David"), t("Samson and Delilah", "Sina Samson at Delila")],
    ref: v("1 Samuel", 20, "35-42") },
  { id: "ic-h-04", level: "hard", icons: "📦🗿💥",
    choices: [t("The ark and the idol Dagon", "Ang kaban at ang diyus-diyosang si Dagon"), t("The fall of Jericho", "Ang pagbagsak ng Jerico"), t("The golden calf", "Ang gintong guya"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo")],
    ref: v("1 Samuel", 5, "1-4") },
  { id: "ic-h-05", level: "hard", icons: "🦴🌬️⚡",
    choices: [t("Ezekiel and the valley of dry bones", "Si Ezekiel at ang libis ng mga tuyong buto"), t("The raising of Lazarus", "Ang pagbuhay kay Lazaro"), t("Elijah and the widow's son", "Si Elias at ang anak ng balo"), t("Daniel's vision", "Ang pangitain ni Daniel")],
    ref: v("Ezekiel", 37, "1-10") },
  { id: "ic-h-06", level: "hard", icons: "🔴🧵🏠",
    choices: [t("Rahab hides the spies", "Itinago ni Rahab ang mga tiktik"), t("The fall of Jericho", "Ang pagbagsak ng Jerico"), t("Jael and Sisera", "Sina Jael at Sisera"), t("The Passover in Egypt", "Ang Paskuwa sa Ehipto")],
    ref: v("Joshua", 2, "1-21") },
  { id: "ic-h-07", level: "hard", icons: "😴🪟🕯️",
    choices: [t("Eutychus falls asleep during Paul's sermon", "Nakatulog si Eutico habang nangangaral si Pablo"), t("Jonah sleeping in the ship", "Natulog si Jonas sa barko"), t("Jesus sleeps in the storm", "Natulog si Jesus sa gitna ng unos"), t("Peter's escape from prison", "Ang pagtakas ni Pedro sa bilangguan")],
    ref: v("Acts", 20, "7-12") },
  { id: "ic-h-08", level: "hard", icons: "🐍🔥🏝️",
    choices: [t("Paul and the snake on Malta", "Si Pablo at ang ahas sa Malta"), t("Adam and Eve in the garden", "Sina Adan at Eba sa hardin"), t("Moses' bronze serpent", "Ang tansong ahas ni Moises"), t("Paul's conversion", "Ang pagbabagong-buhay ni Pablo")],
    ref: v("Acts", 28, "1-6") },
  { id: "ic-h-09", level: "hard", icons: "🔥👄😇",
    choices: [t("Isaiah's lips are touched with a coal", "Ang mga labi ni Isaias ay hinipo ng baga"), t("Moses and the burning bush", "Si Moises at ang nagniningas na palumpong"), t("Pentecost", "Ang Pentecostes"), t("Jeremiah's call", "Ang pagtawag kay Jeremias")],
    ref: v("Isaiah", 6, "5-7") },
  { id: "ic-h-10", level: "hard", icons: "🌙🤼🦵",
    choices: [t("Jacob wrestles with God", "Nakipagbuno si Jacob sa Diyos"), t("Jacob's ladder", "Ang hagdan ni Jacob"), t("Jacob and Esau meet", "Nagkita sina Jacob at Esau"), t("Samson and the lion", "Si Samson at ang leon")],
    ref: v("Genesis", 32, "24-31") },
  { id: "ic-h-11", level: "hard", icons: "🌞↩️🪜",
    choices: [t("The shadow goes back for Hezekiah", "Umurong pabalik ang anino para kay Ezequias"), t("The sun stands still for Joshua", "Tumigil ang araw para kay Josue"), t("Darkness at the cross", "Ang kadiliman sa krus"), t("Jacob's ladder", "Ang hagdan ni Jacob")],
    ref: v("2 Kings", 20, "8-11") },
  { id: "ic-h-12", level: "hard", icons: "🛞📜💧",
    choices: [t("Philip and the Ethiopian official", "Si Felipe at ang opisyal na Etiope"), t("Jesus' baptism", "Ang pagbibinyag kay Jesus"), t("Paul's conversion", "Ang pagbabagong-buhay ni Pablo"), t("Lydia in Philippi", "Si Lydia sa Filipos")],
    ref: v("Acts", 8, "26-39") },
  { id: "ic-h-13", level: "hard", icons: "🐑💧☁️",
    choices: [t("Gideon's fleece", "Ang balahibo ng tupa ni Gideon"), t("The Lost Sheep", "Ang Nawawalang Tupa"), t("Gideon and the 300 men", "Si Gideon at ang 300 tauhan"), t("David the shepherd", "Si David na pastol")],
    ref: v("Judges", 6, "36-40") },
  { id: "ic-h-14", level: "hard", icons: "🪓💧🪵",
    choices: [t("The floating axe head", "Ang palakol na lumutang"), t("Naaman is healed", "Gumaling si Naaman"), t("Noah builds the ark", "Ginawa ni Noe ang arka"), t("Jonah and the big fish", "Si Jonas at ang malaking isda")],
    ref: v("2 Kings", 6, "1-7") },
  { id: "ic-h-15", level: "hard", icons: "🐍🪵👀",
    choices: [t("The bronze serpent in the wilderness", "Ang tansong ahas sa ilang"), t("Paul and the snake on Malta", "Si Pablo at ang ahas sa Malta"), t("Aaron's staff becomes a snake", "Ang tungkod ni Aaron ay naging ahas"), t("Adam and Eve in the garden", "Sina Adan at Eba sa hardin")],
    ref: v("Numbers", 21, "4-9") },
  { id: "ic-h-16", level: "hard", icons: "🎶⛓️🌋",
    choices: [t("Paul and Silas in prison at Philippi", "Sina Pablo at Silas sa bilangguan sa Filipos"), t("Peter's escape from prison", "Ang pagtakas ni Pedro sa bilangguan"), t("Joseph in prison", "Si Jose sa bilangguan"), t("Samson in the temple", "Si Samson sa templo")],
    ref: v("Acts", 16, "25-34") },
  { id: "ic-h-17", level: "hard", icons: "👑🐂🌿",
    choices: [t("Nebuchadnezzar eats grass like an ox", "Kumain ng damo si Nabucodonosor na parang baka"), t("The golden calf", "Ang gintong guya"), t("The fiery furnace", "Ang nagniningas na hurno"), t("Elijah on Mount Carmel", "Si Elias sa Bundok ng Carmelo")],
    ref: v("Daniel", 4, "28-33") },
  { id: "ic-h-18", level: "hard", icons: "🐄🌾🐄",
    choices: [t("Pharaoh's dreams and Joseph", "Ang mga panaginip ni Paraon at si Jose"), t("The ten plagues of Egypt", "Ang sampung salot sa Ehipto"), t("Daniel interprets the king's dream", "Isinalin ni Daniel ang panaginip ng hari"), t("Jacob's ladder", "Ang hagdan ni Jacob")],
    ref: v("Genesis", 41, "1-32") },
  { id: "ic-h-19", level: "hard", icons: "🌾🐑😠",
    choices: [t("Cain and Abel", "Sina Cain at Abel"), t("Jacob and Esau", "Sina Jacob at Esau"), t("Joseph and his brothers", "Si Jose at ang kanyang mga kapatid"), t("Abraham and Lot", "Sina Abraham at Lot")],
    ref: v("Genesis", 4, "2-8") },
  { id: "ic-h-20", level: "hard", icons: "💰😮⚰️",
    choices: [t("Ananias and Sapphira", "Sina Ananias at Safira"), t("Judas betrays Jesus", "Pinagtaksilan ni Judas si Jesus"), t("The rich young ruler", "Ang mayamang batang pinuno"), t("The widow's offering", "Ang abuloy ng balo")],
    ref: v("Acts", 5, "1-10") },
];
