import { t, v, type ScrambleWord } from "./types";

export const SCRAMBLE: ScrambleWord[] = [
  // ---------- EASY ----------
  { id: "sc-e-01", level: "easy", word: t("MOSES", "MOISES"), hint: t("He led Israel out of Egypt", "Pinuno ng Israel palabas ng Ehipto"), ref: v("Exodus", 3, "10") },
  { id: "sc-e-02", level: "easy", word: t("NOAH", "NOE"), hint: t("He built a big boat for the flood", "Nagtayo ng malaking barko para sa baha"), ref: v("Genesis", 6, "14") },
  { id: "sc-e-03", level: "easy", word: t("DAVID", "DAVID"), hint: t("The shepherd boy who became king", "Batang pastol na naging hari"), ref: v("1 Samuel", 16, "13") },
  { id: "sc-e-04", level: "easy", word: t("EDEN", "EDEN"), hint: t("The first garden", "Ang unang hardin"), ref: v("Genesis", 2, "8") },
  { id: "sc-e-05", level: "easy", word: t("ADAM", "ADAN"), hint: t("The first man", "Ang unang lalaki"), ref: v("Genesis", 2, "7") },
  { id: "sc-e-06", level: "easy", word: t("EVE", "EBA"), hint: t("The first woman", "Ang unang babae"), ref: v("Genesis", 3, "20") },
  { id: "sc-e-07", level: "easy", word: t("ABEL", "ABEL"), hint: t("Cain's younger brother, a shepherd", "Nakababatang kapatid ni Cain, isang pastol"), ref: v("Genesis", 4, "2") },
  { id: "sc-e-08", level: "easy", word: t("CAIN", "CAIN"), hint: t("Adam's firstborn son", "Panganay na anak ni Adan"), ref: v("Genesis", 4, "1") },
  { id: "sc-e-09", level: "easy", word: t("RUTH", "RUTH"), hint: t("A Moabite woman who stayed loyal to Naomi", "Babaeng Moabita na nanatiling tapat kay Noemi"), ref: v("Ruth", 1, "16") },
  { id: "sc-e-10", level: "easy", word: t("JOB", "JOB"), hint: t("A man who suffered much but trusted God", "Taong maraming dinanas pero nagtiwala sa Diyos"), ref: v("Job", 1, "1") },
  { id: "sc-e-11", level: "easy", word: t("ARK", "ARKA"), hint: t("What Noah built to survive the flood", "Itinayo ni Noe para makaligtas sa baha"), ref: v("Genesis", 6, "14") },
  { id: "sc-e-12", level: "easy", word: t("LAMB", "KORDERO"), hint: t("John called Jesus the \"___ of God\"", "Tawag ni Juan kay Jesus: \"___ ng Diyos\""), ref: v("John", 1, "29") },
  { id: "sc-e-13", level: "easy", word: t("STAR", "BITUIN"), hint: t("The wise men followed it to Jesus", "Sinundan ng mga pantas papunta kay Jesus"), ref: v("Matthew", 2, "2") },
  { id: "sc-e-14", level: "easy", word: t("FISH", "ISDA"), hint: t("Swallowed Jonah", "Lumunok kay Jonas"), ref: v("Jonah", 1, "17") },
  { id: "sc-e-15", level: "easy", word: t("BREAD", "TINAPAY"), hint: t("Jesus said, \"I am the ___ of life\"", "Sabi ni Jesus, \"Ako ang ___ ng buhay\""), ref: v("John", 6, "35") },
  { id: "sc-e-16", level: "easy", word: t("WINE", "ALAK"), hint: t("Jesus made it from water at Cana", "Ginawa ni Jesus mula sa tubig sa Cana"), ref: v("John", 2, "9") },
  { id: "sc-e-17", level: "easy", word: t("KING", "HARI"), hint: t("Saul and David were this over Israel", "Sina Saul at David ay ganito sa Israel"), ref: v("1 Samuel", 10, "24") },
  { id: "sc-e-18", level: "easy", word: t("GOD", "DIYOS"), hint: t("He created the heavens and the earth", "Lumikha ng langit at lupa"), ref: v("Genesis", 1, "1") },
  { id: "sc-e-19", level: "easy", word: t("SIN", "SALA"), hint: t("Jesus died to take it away", "Namatay si Jesus para alisin ito"), ref: v("Romans", 3, "23") },
  { id: "sc-e-20", level: "easy", word: t("LIGHT", "LIWANAG"), hint: t("God made it on the first day", "Ginawa ng Diyos sa unang araw"), ref: v("Genesis", 1, "3") },
  { id: "sc-e-21", level: "easy", word: t("SEA", "DAGAT"), hint: t("Moses parted the Red one", "Hinati ni Moises ang Pula nito"), ref: v("Exodus", 14, "21") },
  { id: "sc-e-22", level: "easy", word: t("ROCK", "BATO"), hint: t("David used one to defeat Goliath", "Ginamit ni David laban kay Goliat"), ref: v("1 Samuel", 17, "49") },
  { id: "sc-e-23", level: "easy", word: t("LAMP", "ILAW"), hint: t("Your word is a ___ to my feet", "Ang salita mo ay ___ sa aking mga paa"), ref: v("Psalms", 119, "105") },
  { id: "sc-e-24", level: "easy", word: t("JOHN", "JUAN"), hint: t("The disciple Jesus loved, who wrote a Gospel", "Alagad na minahal ni Jesus, sumulat ng Ebanghelyo"), ref: v("John", 21, "20") },
  { id: "sc-e-25", level: "easy", word: t("PAUL", "PABLO"), hint: t("Once called Saul, he wrote many letters", "Dating tinawag na Saulo, sumulat ng maraming sulat"), ref: v("Acts", 13, "9") },
  { id: "sc-e-26", level: "easy", word: t("PETER", "PEDRO"), hint: t("The fisherman who denied Jesus three times", "Mangingisdang tatlong beses na nagkaila kay Jesus"), ref: v("Luke", 22, "61") },
  { id: "sc-e-27", level: "easy", word: t("ISAAC", "ISAAC"), hint: t("Son of Abraham and Sarah", "Anak nina Abraham at Sara"), ref: v("Genesis", 21, "3") },
  { id: "sc-e-28", level: "easy", word: t("JESUS", "HESUS"), hint: t("The Savior, born in Bethlehem", "Ang Tagapagligtas na isinilang sa Betlehem"), ref: v("Matthew", 1, "21") },
  { id: "sc-e-29", level: "easy", word: t("CROSS", "KRUS"), hint: t("Where Jesus was crucified", "Dito ipinako si Jesus"), ref: v("John", 19, "17") },
  { id: "sc-e-30", level: "easy", word: t("AMEN", "AMEN"), hint: t("The word we say at the end of a prayer", "Salitang sinasabi sa dulo ng panalangin"), ref: v("Matthew", 6, "13") },

  // ---------- MEDIUM ----------
  { id: "sc-m-01", level: "medium", word: t("FAITH", "TIWALA"), hint: t("Being sure of what we hope for", "Pagtitiyak sa mga bagay na inaasahan"), ref: v("Hebrews", 11, "1") },
  { id: "sc-m-02", level: "medium", word: t("PEACE", "KAPAYAPAAN"), hint: t("Jesus said, \"___ I leave with you\"", "Sabi ni Jesus, \"Iniiwan ko sa inyo ang ___\""), ref: v("John", 14, "27") },
  { id: "sc-m-03", level: "medium", word: t("GRACE", "BIYAYA"), hint: t("God's free, undeserved favor", "Libre at hindi pinaghirapang kabutihan ng Diyos"), ref: v("Ephesians", 2, "8") },
  { id: "sc-m-04", level: "medium", word: t("PRAYER", "PANALANGIN"), hint: t("Talking with God", "Pakikipag-usap sa Diyos"), ref: v("Philippians", 4, "6") },
  { id: "sc-m-05", level: "medium", word: t("ANGEL", "ANGHEL"), hint: t("Gabriel is one; he brought God's messages", "Si Gabriel ay isa; nagdala ng mensahe ng Diyos"), ref: v("Luke", 1, "26") },
  { id: "sc-m-06", level: "medium", word: t("MIRACLE", "MILAGRO"), hint: t("Jesus did many, like healing the blind", "Marami ang ginawa ni Jesus, tulad ng pagpapagaling ng bulag"), ref: v("John", 2, "11") },
  { id: "sc-m-07", level: "medium", word: t("JORDAN", "JORDAN"), hint: t("The river where Jesus was baptized", "Ilog kung saan binyagan si Jesus"), ref: v("Matthew", 3, "13") },
  { id: "sc-m-08", level: "medium", word: t("ISRAEL", "ISRAEL"), hint: t("The new name God gave Jacob", "Bagong pangalang ibinigay ng Diyos kay Jacob"), ref: v("Genesis", 32, "28") },
  { id: "sc-m-09", level: "medium", word: t("EGYPT", "EHIPTO"), hint: t("The land where Israel was enslaved", "Lupaing pinagkaalipinan sa Israel"), ref: v("Exodus", 1, "13") },
  { id: "sc-m-10", level: "medium", word: t("JOSEPH", "JOSE"), hint: t("Sold by his brothers, later ruled Egypt", "Ibinenta ng mga kapatid, naging pinuno sa Ehipto"), ref: v("Genesis", 37, "28") },
  { id: "sc-m-11", level: "medium", word: t("JACOB", "JACOB"), hint: t("Esau's twin brother", "Kambal ni Esau"), ref: v("Genesis", 25, "26") },
  { id: "sc-m-12", level: "medium", word: t("ESTHER", "ESTER"), hint: t("The queen who saved her people", "Reynang nagligtas sa kanyang bayan"), ref: v("Esther", 4, "14") },
  { id: "sc-m-13", level: "medium", word: t("SAMSON", "SANSON"), hint: t("A strong judge whose strength was in his hair", "Malakas na hukom na nasa buhok ang lakas"), ref: v("Judges", 16, "17") },
  { id: "sc-m-14", level: "medium", word: t("SOLOMON", "SALOMON"), hint: t("The wise king who built the temple", "Pantas na haring nagtayo ng templo"), ref: v("1 Kings", 6, "1") },
  { id: "sc-m-15", level: "medium", word: t("ELIJAH", "ELIAS"), hint: t("The prophet fed by ravens", "Propetang pinakain ng mga uwak"), ref: v("1 Kings", 17, "6") },
  { id: "sc-m-16", level: "medium", word: t("DANIEL", "DANIEL"), hint: t("He was thrown into the lions' den", "Inihagis sa yungib ng mga leon"), ref: v("Daniel", 6, "16") },
  { id: "sc-m-17", level: "medium", word: t("JONAH", "JONAS"), hint: t("The prophet sent to Nineveh", "Propetang ipinadala sa Nineve"), ref: v("Jonah", 1, "2") },
  { id: "sc-m-18", level: "medium", word: t("SAMUEL", "SAMUEL"), hint: t("The boy who heard God call at night", "Batang narinig ang tawag ng Diyos sa gabi"), ref: v("1 Samuel", 3, "10") },
  { id: "sc-m-19", level: "medium", word: t("SATAN", "SATANAS"), hint: t("The tempter who tested Jesus in the desert", "Manunukso na sumubok kay Jesus sa ilang"), ref: v("Matthew", 4, "1") },
  { id: "sc-m-20", level: "medium", word: t("TEMPLE", "TEMPLO"), hint: t("Solomon built it in Jerusalem", "Itinayo ni Solomon sa Jerusalem"), ref: v("1 Kings", 6, "1") },
  { id: "sc-m-21", level: "medium", word: t("SABBATH", "SABADO"), hint: t("The seventh day of rest", "Ikapitong araw ng pamamahinga"), ref: v("Exodus", 20, "8") },
  { id: "sc-m-22", level: "medium", word: t("PSALMS", "AWIT"), hint: t("The book of songs and prayers, many by David", "Aklat ng mga awit at dalangin, marami kay David"), ref: v("Psalms", 23, "1") },
  { id: "sc-m-23", level: "medium", word: t("MANNA", "MANNA"), hint: t("Bread from heaven in the wilderness", "Tinapay mula langit sa ilang"), ref: v("Exodus", 16, "31") },
  { id: "sc-m-24", level: "medium", word: t("GOSPEL", "EBANGHELYO"), hint: t("The good news about Jesus", "Magandang balita tungkol kay Jesus"), ref: v("Mark", 1, "1") },
  { id: "sc-m-25", level: "medium", word: t("PROPHET", "PROPETA"), hint: t("One who speaks God's message, like Isaiah", "Nagsasalita ng mensahe ng Diyos, tulad ni Isaias"), ref: v("Isaiah", 6, "8") },
  { id: "sc-m-26", level: "medium", word: t("PHARAOH", "PARAON"), hint: t("The king of Egypt in Moses' time", "Hari ng Ehipto noong panahon ni Moises"), ref: v("Exodus", 5, "1") },
  { id: "sc-m-27", level: "medium", word: t("LEPROSY", "KETONG"), hint: t("A skin disease Jesus healed", "Sakit sa balat na pinagaling ni Jesus"), ref: v("Luke", 5, "13") },
  { id: "sc-m-28", level: "medium", word: t("SPIRIT", "ESPIRITU"), hint: t("The Holy ___ came at Pentecost", "Ang Banal na ___ ay dumating noong Pentecostes"), ref: v("Acts", 2, "4") },
  { id: "sc-m-29", level: "medium", word: t("MERCY", "AWA"), hint: t("God's kindness to those who don't deserve punishment", "Kabaitan ng Diyos sa hindi dapat parusahan"), ref: v("Micah", 6, "8") },
  { id: "sc-m-30", level: "medium", word: t("ABRAHAM", "ABRAHAM"), hint: t("The father of faith who left Ur", "Ama ng pananampalataya na umalis sa Ur"), ref: v("Genesis", 12, "1") },

  // ---------- HARD ----------
  { id: "sc-h-01", level: "hard", word: t("BETHLEHEM", "BETLEHEM"), hint: t("The town where Jesus was born", "Bayan kung saan isinilang si Jesus"), ref: v("Matthew", 2, "1") },
  { id: "sc-h-02", level: "hard", word: t("NAZARETH", "NAZARET"), hint: t("The town where Jesus grew up", "Bayan kung saan lumaki si Jesus"), ref: v("Luke", 2, "39") },
  { id: "sc-h-03", level: "hard", word: t("JERUSALEM", "JERUSALEM"), hint: t("The holy city where the temple stood", "Banal na lungsod kung nasaan ang templo"), ref: v("Psalms", 122, "6") },
  { id: "sc-h-04", level: "hard", word: t("GETHSEMANE", "GETSEMANI"), hint: t("The garden where Jesus prayed before his arrest", "Hardin kung saan nanalangin si Jesus bago dakpin"), ref: v("Matthew", 26, "36") },
  { id: "sc-h-05", level: "hard", word: t("DISCIPLE", "ALAGAD"), hint: t("A follower and learner of Jesus", "Tagasunod at nag-aaral kay Jesus"), ref: v("Matthew", 28, "19") },
  { id: "sc-h-06", level: "hard", word: t("COVENANT", "TIPAN"), hint: t("A solemn promise between God and his people", "Taimtim na pangako ng Diyos sa kanyang bayan"), ref: v("Genesis", 9, "9") },
  { id: "sc-h-07", level: "hard", word: t("FORGIVENESS", "PAGPAPATAWAD"), hint: t("Jesus taught us to give it to those who wrong us", "Itinuro ni Jesus na ibigay sa mga nagkasala sa atin"), ref: v("Ephesians", 4, "32") },
  { id: "sc-h-08", level: "hard", word: t("SALVATION", "KALIGTASAN"), hint: t("Being rescued by Jesus through faith", "Pagkaligtas kay Jesus sa pamamagitan ng pananampalataya"), ref: v("Ephesians", 2, "8") },
  { id: "sc-h-09", level: "hard", word: t("TABERNACLE", "TOLDA"), hint: t("The tent where Israel worshiped in the wilderness", "Tolda ng pagsamba ng Israel sa ilang"), ref: v("Exodus", 40, "34") },
  { id: "sc-h-10", level: "hard", word: t("JEREMIAH", "JEREMIAS"), hint: t("The weeping prophet", "Ang propetang tumatangis"), ref: v("Jeremiah", 29, "11") },
  { id: "sc-h-11", level: "hard", word: t("EZEKIEL", "EZEKIEL"), hint: t("The prophet who saw the valley of dry bones", "Propetang nakakita sa libis ng mga tuyong buto"), ref: v("Ezekiel", 37, "1") },
  { id: "sc-h-12", level: "hard", word: t("NEHEMIAH", "NEHEMIAS"), hint: t("He led the rebuilding of Jerusalem's wall", "Namuno sa muling pagtatayo ng pader ng Jerusalem"), ref: v("Nehemiah", 2, "17") },
  { id: "sc-h-13", level: "hard", word: t("MELCHIZEDEK", "MELQUISEDEC"), hint: t("The priest-king who blessed Abraham", "Pari-haring nagpala kay Abraham"), ref: v("Genesis", 14, "18") },
  { id: "sc-h-14", level: "hard", word: t("NEBUCHADNEZZAR", "NABUCODONOSOR"), hint: t("The king of Babylon who built a golden statue", "Hari ng Babilonia na gumawa ng gintong rebulto"), ref: v("Daniel", 3, "1") },
  { id: "sc-h-15", level: "hard", word: t("ZACCHAEUS", "ZAQUEO"), hint: t("The short tax collector who climbed a tree", "Maikling maniningil ng buwis na umakyat sa puno"), ref: v("Luke", 19, "4") },
  { id: "sc-h-16", level: "hard", word: t("BARTIMAEUS", "BARTIMEO"), hint: t("The blind beggar of Jericho healed by Jesus", "Bulag na pulubi sa Jerico na pinagaling ni Jesus"), ref: v("Mark", 10, "46") },
  { id: "sc-h-17", level: "hard", word: t("GOLGOTHA", "GOLGOTA"), hint: t("The place of the skull, where Jesus was crucified", "Lugar ng bungo, kung saan ipinako si Jesus"), ref: v("John", 19, "17") },
  { id: "sc-h-18", level: "hard", word: t("CAPERNAUM", "CAPERNAUM"), hint: t("A town by the Sea of Galilee where Jesus lived and taught", "Bayan sa tabi ng Dagat ng Galilea kung saan tumira at nagturo si Jesus"), ref: v("Matthew", 4, "13") },
  { id: "sc-h-19", level: "hard", word: t("PHILISTINE", "PILISTEO"), hint: t("Goliath belonged to this people", "Si Goliat ay kabilang sa lahing ito"), ref: v("1 Samuel", 17, "4") },
  { id: "sc-h-20", level: "hard", word: t("PHILIPPIANS", "FILIPOS"), hint: t("Paul's letter of joy, written from prison", "Sulat ng kagalakan ni Pablo mula sa bilangguan"), ref: v("Philippians", 4, "4") },
  { id: "sc-h-21", level: "hard", word: t("CORINTHIANS", "CORINTO"), hint: t("Paul wrote two letters to this church about love and unity", "Dalawang sulat ni Pablo sa iglesyang ito tungkol sa pag-ibig at pagkakaisa"), ref: v("1 Corinthians", 13, "13") },
  { id: "sc-h-22", level: "hard", word: t("ECCLESIASTES", "ECLESIASTES"), hint: t("The book that says there is a time for everything", "Aklat na nagsasabing may panahon ang lahat ng bagay"), ref: v("Ecclesiastes", 3, "1") },
  { id: "sc-h-23", level: "hard", word: t("DEUTERONOMY", "DEUTERONOMIO"), hint: t("The fifth book of the Bible", "Ikalimang aklat ng Biblia"), ref: v("Deuteronomy", 6, "4") },
  { id: "sc-h-24", level: "hard", word: t("SANHEDRIN", "SANHEDRIN"), hint: t("The Jewish council that tried Jesus", "Konseho ng mga Judio na humatol kay Jesus"), ref: v("Mark", 14, "55") },
  { id: "sc-h-25", level: "hard", word: t("PENTECOST", "PENTECOSTES"), hint: t("The day the Holy Spirit came upon the believers", "Araw na dumating ang Banal na Espiritu sa mga mananampalataya"), ref: v("Acts", 2, "1") },
  { id: "sc-h-26", level: "hard", word: t("BARNABAS", "BERNABE"), hint: t("The \"son of encouragement\" who traveled with Paul", "Ang \"anak ng pampatibay\" na kasama ni Pablo"), ref: v("Acts", 4, "36") },
  { id: "sc-h-27", level: "hard", word: t("SAMARITAN", "SAMARITANO"), hint: t("In Jesus' story, he stopped to help the wounded man", "Sa kuwento ni Jesus, tumigil siya para tulungan ang sugatan"), ref: v("Luke", 10, "33") },
  { id: "sc-h-28", level: "hard", word: t("PHARISEE", "FARISEO"), hint: t("A strict religious leader who often opposed Jesus", "Mahigpit na lider-relihiyoso na madalas tumutol kay Jesus"), ref: v("Luke", 18, "10") },
  { id: "sc-h-29", level: "hard", word: t("JEHOSHAPHAT", "JEHOSAFAT"), hint: t("The king of Judah who sent singers ahead of his army", "Hari ng Juda na nagpauna ng mga mang-aawit sa kanyang hukbo"), ref: v("2 Chronicles", 20, "21") },
  { id: "sc-h-30", level: "hard", word: t("BEELZEBUB", "BEELZEBUB"), hint: t("A name the Pharisees used for the prince of demons", "Pangalang ginamit ng mga Fariseo sa pinuno ng mga demonyo"), ref: v("Matthew", 12, "24") },
];
