// Writes src/lib/content/search-index.ts: titles of every Course and Journey
// lesson, so Search stays small. Run after adding or renaming lessons:
//   npx tsx scripts/build-search-index.mts
import { writeFileSync } from "node:fs";
import { COURSES } from "../src/lib/content/courses/index";
import { JOURNEY_LEVELS, findLesson } from "../src/lib/content/journey";

const rows: { href: string; kind: "course" | "lesson" | "journey"; en: string; tl: string; sub: { en: string; tl: string } }[] = [];
for (const c of COURSES) {
  rows.push({ href: `/courses/${c.id}`, kind: "course", en: c.title.en, tl: c.title.tl, sub: { en: "Course", tl: "Course" } });
  c.lessons.forEach((l, i) =>
    rows.push({ href: `/courses/${c.id}/${l.id}`, kind: "lesson", en: l.title.en, tl: l.title.tl, sub: { en: `${c.title.en} · Lesson ${i + 1}`, tl: `${c.title.tl} · Aralin ${i + 1}` } })
  );
}
for (const lv of JOURNEY_LEVELS)
  for (const id of lv.lessonIds) {
    const l = findLesson(id)!;
    rows.push({ href: `/journey/lessons/${id}`, kind: "journey", en: l.title.en, tl: l.title.tl, sub: { en: `Journey · Level ${lv.level}`, tl: `Journey · Level ${lv.level}` } });
  }
writeFileSync(
  "src/lib/content/search-index.ts",
  `/** Generated by scripts/build-search-index.mts: lesson titles for Search. Do not edit by hand. */\nexport const SEARCH_INDEX = ${JSON.stringify(rows)} as const;\n`
);
console.log(rows.length, "rows");
